export const INSTRUMENTS_BLACKLIST = [
  'AUDCNH',
  'CADSGD',
  'ETHCNH',
  '100GBP',
  '200AUD',
  '225JPY',
  'CHN50USD',
  'D30EUR',
  'E35EUR',
  'E50EUR',
  'F40EUR',
  'H33HKD',
  'NASUSD',
  'SPXUSD',
  'U30USD'
];

export const INSTRUMENT_LABELS: Array<{
  label: string;
}> = [
  { label: 'ADAUSD' },
  { label: 'AUDCAD' },
  { label: 'AUDCHF' },
  { label: 'AUDJPY' },
  { label: 'AUDNZD' },
  { label: 'AUDUSD' },
  { label: 'AUS200' },
  { label: 'BTCUSD' },
  { label: 'CADCHF' },
  { label: 'CADJPY' },
  { label: 'CHNIND' },
  { label: 'CHFJPY' },
  { label: 'DOTUSD' },
  { label: 'ETHUSD' },
  { label: 'EU50' },
  { label: 'EURAUD' },
  { label: 'EURCAD' },
  { label: 'EURCHF' },
  { label: 'EURGBP' },
  { label: 'EURJPY' },
  { label: 'EURNZD' },
  { label: 'EURUSD' },
  { label: 'FRA40' },
  { label: 'EU50' },
  { label: 'GBPAUD' },
  { label: 'GBPCAD' },
  { label: 'GBPCHF' },
  { label: 'GBPJPY' },
  { label: 'GBPNZD' },
  { label: 'GBPUSD' },
  { label: 'GER30' },
  { label: 'HKIND' },
  { label: 'ITA40' },
  { label: 'JAP225' },
  { label: 'LTCUSD' },
  { label: 'NZDCAD' },
  { label: 'NZDCHF' },
  { label: 'NZDJPY' },
  { label: 'NZDUSD' },
  { label: 'SPA35' },
  { label: 'UK100' },
  { label: 'US30' },
  { label: 'US100' },
  { label: 'US500' },
  { label: 'USDCAD' },
  { label: 'USDCHF' },
  { label: 'USDHKD' },
  { label: 'USDJPY' },
  { label: 'XAGUSD' },
  { label: 'XAUUSD' },
  { label: 'XLMUSD' },
  { label: 'XPDUSD' },
  { label: 'XPTUSD' },
  { label: 'XRPUSD' }
];
